language: clojure
requires: sudo
env:
  global: 
  matrix:
  - TEST_DIR=cortex
  - TEST_DIR=datasets
  - TEST_DIR=compute
branches:
  only:
  - master
jdk: oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_4e2073fd950b_key -iv $encrypted_4e2073fd950b_iv -in profiles.clj.enc -out profiles.clj -d
- wget https://releases.hashicorp.com/vault/0.6.1/vault_0.6.1_linux_amd64.zip -O vault.zip
- unzip vault.zip
- export PATH=$PATH:$PWD
- mkdir -p ~/.lein && cp profiles.clj ~/.lein/profiles.clj

install:
- cd $TEST_DIR && lein deps
script:
- lein test
after_success:
- lein deploy clojars
